# Generated by Django 5.1.5 on 2025-02-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.SmallIntegerField(choices=[('1', 'Active'), ('2', 'Inactive')], max_length=1),
        ),
    ]
